const people=[
 {id:'ema',name:'Ema Novotná',initial:'E',tone:'tone-blue',time:'teď',preview:'Jo, to zní skvěle! ✨',online:true,unread:true,messages:[['them','Ahoj! Jak se máš?'],['mine','Dobře, díky. Co ty?'],['them','Jo, to zní skvěle! ✨']]},
 {id:'matej',name:'Matěj Kříž',initial:'M',tone:'tone-purple',time:'10:42',preview:'Posílám ti ten track 🎧',online:true,messages:[['them','Posílám ti ten track 🎧']]},
 {id:'klara',name:'Klára Vítková',initial:'K',tone:'tone-orange',time:'Včera',preview:'Mám pro tebe tip na víkend',unread:true,messages:[['them','Mám pro tebe tip na víkend']]},
 {id:'dominik',name:'Dominik',initial:'D',tone:'tone-green',time:'Po',preview:'Díky, ozvu se večer.',verified:true,messages:[['mine','Díky za včerejšek!'],['them','Díky, ozvu se večer.']]},
 {id:'adam',name:'Adam Svoboda',initial:'A',tone:'tone-sand',time:'Ne',preview:'To místo je fakt krásný.',messages:[['them','To místo je fakt krásný.']]},
 {id:'niky',name:'Nikola',initial:'N',tone:'tone-pink',time:'So',preview:'❤️ Líbí se mi „Už se těším“',messages:[['mine','Už se těším'],['them','❤️']]}
];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];let activePerson=null;let unreadOnly=false;
function safe(text){return String(text).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function getSaved(){try{return JSON.parse(localStorage.getItem('link-chats-v1')||'{}')}catch{return {}}}
function save(){localStorage.setItem('link-chats-v1',JSON.stringify(people.map(({id,messages,unread})=>({id,messages,unread}))))}
function restore(){const stored=getSaved();stored.forEach(item=>{const p=people.find(x=>x.id===item.id);if(p&&Array.isArray(item.messages)){p.messages=item.messages;p.unread=item.unread}})}
function lastText(p){const msg=p.messages.at(-1);return msg?msg[1]:p.preview}
function renderList(query=''){
 const list=$('#chat-list'),q=query.trim().toLocaleLowerCase('cs');let result=people.filter(p=>(!unreadOnly||p.unread)&&(!q||`${p.name} ${lastText(p)}`.toLocaleLowerCase('cs').includes(q)));
 list.innerHTML=result.map(p=>`<button class="chat-row" data-chat="${p.id}"><span class="avatar ${p.tone}">${p.initial}</span><span class="chat-copy"><span class="chat-title"><strong>${safe(p.name)}</strong>${p.verified?'<span class="verified" aria-label="Ověřeno">✓</span>':''}</span><span class="chat-preview">${safe(lastText(p))}</span></span><span class="chat-meta"><span class="chat-time">${p.time}</span>${p.unread?'<span class="unread-dot" aria-label="Nepřečteno"></span>':''}</span></button>`).join('');$('#empty-state').classList.toggle('hidden',result.length>0);
}
function timeLabel(){return new Intl.DateTimeFormat('cs-CZ',{hour:'2-digit',minute:'2-digit'}).format(new Date())}
function renderMessages(){if(!activePerson)return;const box=$('#messages');box.innerHTML='<div class="day-divider">Dnes</div>'+activePerson.messages.map(([from,text,time])=>`<div class="message ${from==='mine'?'mine':'them'}">${safe(text)}<span class="message-time">${time||timeLabel()}</span></div>`).join('');box.scrollTop=box.scrollHeight}
function openChat(id){activePerson=people.find(p=>p.id===id);if(!activePerson)return;activePerson.unread=false;$('#chat-name').textContent=activePerson.name;$('#chat-status').textContent=activePerson.online?'Aktivní nyní':'LINK';$('#chat-avatar').textContent=activePerson.initial;$('#chat-avatar').className=`avatar ${activePerson.tone}`;renderMessages();$('#chat-overlay').classList.add('open');$('#chat-overlay').setAttribute('aria-hidden','false');document.body.style.overflow='hidden';setTimeout(()=>$('#message-input').focus({preventScroll:true}),200);save();renderList($('#search').value)}
function closeChat(){$('#chat-overlay').classList.remove('open');$('#chat-overlay').setAttribute('aria-hidden','true');document.body.style.overflow='';activePerson=null}
function showToast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.classList.remove('show'),2300)}
function modal(title,copy,extra='',eyebrow='LINK'){ $('#modal-title').textContent=title;$('#modal-copy').textContent=copy;$('#modal-extra').innerHTML=extra;$('#modal-eyebrow').textContent=eyebrow;$('#modal').showModal() }
function changeTab(tab){closeChat();$$('.screen').forEach(x=>x.classList.remove('active'));$(`#${tab}-screen`).classList.add('active');$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));window.scrollTo({top:0,behavior:'smooth'})}
function renderMoments(){const feed=$('#moment-feed');if(feed.dataset.ready)return;feed.dataset.ready='1';feed.innerHTML=[['Ema','Dnes je všechno nějak lehčí. 🌤','tone-blue','2 h'],['Matěj','Večer ven? Mám volno.','tone-purple','4 h']].map(([name,text,tone,time])=>`<article class="moment-card"><div class="moment-head"><span class="avatar ${tone}">${name[0]}</span><span><strong>${name}</strong><small>${time}</small></span></div><div class="moment-content">${safe(text)}</div></article>`).join('')}
function addMoment(){modal('Sdílejte moment','Malý kousek vašeho dne pro lidi, které máte blízko.','<label class="sr-only" for="moment-input">Text momentu</label><input id="moment-input" maxlength="120" placeholder="Co máte právě v hlavě?" style="width:100%;border:1px solid #e4e4df;border-radius:12px;padding:12px;font:inherit;background:white">','MOMENTY')}
function handleAction(action){switch(action){case'close-chat':closeChat();break;case'home':changeTab('chats');break;case'install-help':modal('LINK patří na plochu','Přidejte si LINK do iPhonu a otevřete ho jako vlastní aplikaci.','<div class="install-steps"><div><b>1</b> Otevřete tuto stránku v Safari</div><div><b>2</b> Klepněte na Sdílet <strong>□↑</strong></div><div><b>3</b> Zvolte „Přidat na plochu“</div></div>','INSTALACE');break;case'add-note':modal('Vaše poznámka','Krátká věta, kterou uvidí vaši přátelé.','<input id="note-input" maxlength="55" placeholder="Co se vám honí hlavou?" style="width:100%;border:1px solid #e4e4df;border-radius:12px;padding:12px;font:inherit;background:white">','POZNÁMKY');break;case'new-message':modal('Nová zpráva','Vyberte někoho ze svých konverzací.',people.map(p=>`<button class="settings-row" data-pick-chat="${p.id}"><span class="avatar ${p.tone}" style="width:32px;height:32px">${p.initial}</span><strong>${safe(p.name)}</strong><b>›</b></button>`).join(''),'NOVÁ ZPRÁVA');break;case'filter-unread':unreadOnly=!unreadOnly;$('.text-button').innerHTML=unreadOnly?'Nepřečtené <span>⌄</span>':'Všechny <span>⌄</span>';renderList($('#search').value);break;case'chat-info':modal(activePerson?.name||'Konverzace','Tento prostor je určený jen vám a vašemu člověku.','<div class="install-steps">Zprávy jsou v této ukázce uložené pouze v tomto zařízení.</div>','INFO');break;case'attach':showToast('Přílohy budou brzy k dispozici');break;case'add-moment':addMoment();break;case'edit-profile':modal('Váš profil','Úprava profilu bude součástí další verze.','<div class="install-steps">Profilová stránka · Status · Fotografie</div>','PROFIL');break;case'privacy':modal('Soukromí','Vaše soukromí máte pod kontrolou.','<div class="install-steps">Viditelnost profilu<br>Žádosti o propojení<br>Blokované účty</div>','NASTAVENÍ');break;case'about':modal('Jednoduše blíž.','LINK je klidnější prostor pro zprávy a malé momenty s lidmi, na kterých záleží.','<div class="install-steps">Návrh aplikace · Preview 1.0</div>','O LINKU');break;case'modal-close':$('#modal').close();break}}
document.addEventListener('click',e=>{const action=e.target.closest('[data-action]')?.dataset.action;if(action)handleAction(action);const tab=e.target.closest('[data-tab]')?.dataset.tab;if(tab)changeTab(tab);const chat=e.target.closest('[data-chat]')?.dataset.chat;if(chat)openChat(chat);const pick=e.target.closest('[data-pick-chat]')?.dataset.pickChat;if(pick){$('#modal').close();setTimeout(()=>openChat(pick),80)}const note=e.target.closest('[data-note]')?.dataset.note;if(note)modal(note,'Ema sdílela poznámku se svými přáteli.','','POZNÁMKA')});
$('#search').addEventListener('input',e=>renderList(e.target.value));$('#message-form').addEventListener('submit',e=>{e.preventDefault();const input=$('#message-input'),value=input.value.trim();if(!value||!activePerson)return;activePerson.messages.push(['mine',value,timeLabel()]);activePerson.time='teď';input.value='';save();renderMessages();renderList($('#search').value)});
$('#modal').addEventListener('click',e=>{if(e.target===$('#modal'))$('#modal').close()});$('#modal').addEventListener('close',()=>{const note=$('#note-input');if(note?.value.trim()){const card=document.createElement('button');card.className='note-card';card.innerHTML=`<span class="note-avatar note-photo tone-green">Š</span><span class="note-bubble">${safe(note.value.trim())}</span><span class="note-name">Vy</span>`;$('#notes-row').insertBefore(card,$('#notes-row').children[1]);showToast('Poznámka je připravená ke sdílení')}const moment=$('#moment-input');if(moment?.value.trim()){const card=document.createElement('article');card.className='moment-card';card.innerHTML=`<div class="moment-head"><span class="avatar avatar-self">Š</span><span><strong>Vy</strong><small>Právě teď</small></span></div><div class="moment-content">${safe(moment.value.trim())}</div>`;$('#moment-feed').prepend(card);$('#moment-feed').dataset.ready='1';showToast('Moment přidán')} });
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
restore();renderList();renderMoments();
